#import "../design.typ": *

#pagebreak(weak: true)

#section("Index Locorum")

#block(inset: (bottom: 2mm), text(font: body_family, size: 9pt, style: "italic", fill: ink_gray)[
  Every passage this essay engages, gathered under its source and sorted by
  reference. Generated by `inkhaven index-locorum` from the loci the prose
  actually cites; the movement in which each is cited follows it. Works cited
  whole — the King Follett discourse and Snow's couplet — carry no locus and so
  do not appear here.
])

#locorum_source("Critique of Practical Reason", "kant-cpracr")
#locus("Ak. 5:32", "II")
#locus("Ak. 5:122", "II–IV")
#locus("Ak. 5:124", "III")
#locus("Ak. 5:126", "III")

#locorum_source("Critique of Pure Reason", "kant-cpr")
#locus("A51/B75", "III")
#locus("A538/B566", "II")
#locus("A546/B574", "II")

#locorum_source("The Book of Mormon", "book-of-mormon")
#locus("3 Nephi 12:48", "III")
#locus("Moroni 10:5", "III")
#locus("Moroni 10:32", "III")

#locorum_source("The Holy Bible: World English Bible", "bible")
#locus("1 John 3:2", "III, V")
#locus("Isaiah 28:10", "II")
#locus("John 3:16", "V")
#locus("Matthew 5:48", "II")
